version: '3'
services:
  grin-wallet:
    container_name: grin-wallet
    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - 3413:3413
      - 3414:3414
      - 3415:3415
      - 3416:3416
    volumes:
      - ./wallets/wallet.seed:/root/.grin/main/wallet_data/wallet.seed
      - ./grin-server.toml:/grin-wallet/grin-server.toml